name = ["Rust ", "Argentina"]
description = "Anteriormente Rust Argentina, hoy una comunidad internacional."
link = "https://t.me/rust_lang_es"
icon = "telegram"
brand_src = "./rust-argentina.webp"
brand_alt = "Logo de Rust Argentina"
