name = ["Salamandra ", "Devs"]
description = "Comunidad de Programación en general."
link = "https://t.me/salamandradevs"
icon = "telegram"
brand_src = "./Salamandra.webp"
brand_alt = "Logo de Salamandra Devs"
