name = ["Graphul"]
description = "Un framework web basado en Axum"
link = "https://graphul-rs.github.io"
brand_src = "https://graphul-rs.github.io/img/logo.svg"
button_link = "https://github.com/SamuelBonilla"
button_text = "Samuel Bonilla"
brand_as_letter = false
button_bg_color = "black"
